idf_textures_path: /var/Left4Dead/assets/Soldier_IDF/
scout_textures_path: /var/Left4Dead/assets/Soldier_Scout/
p90_textures_path: /var/Left4Dead/assets/Soldier_P90/

zombie_textures_path: /var/Left4Dead/assets/Zombie/
spear_textures_path: /var/Left4Dead/assets/Spear/
venom_textures_path: /var/Left4Dead/assets/Venom/
witch_textures_path: /var/Left4Dead/assets/Witch/

crater_textures_path: /var/Left4Dead/assets/backgrounds/War1/Bright/
projectiles_textures_path: /var/Left4Dead/assets/
player_hearts_texture_path: /var/Left4Dead/assets/Mis/heart.jpg

background_texture_path: /var/Left4Dead/assets/backgrounds/War1/Bright/
icon_path: /var/Left4Dead/assets/

path_fonts: /var/Left4Dead/assets/Fonts/

music_path: /var/Left4Dead/assets/Audio/Music/
sound_effects_path: /var/Left4Dead/assets/Audio/SoundEffects/
volumne_music: 64                                                #0 is min, 128 is max