---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/nath/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.0-71-generic - x86_64
...
